@startuml
'https://plantuml.com/class-diagram

class Gradebook{
    Assignment: List

    addStudent(Student)
    removeStudent(Student)
    lookupStudentGrades(Student)

    getAssignmentStatistics(Assignment)
    addAssignment(Assignment)
    removeAssignment(Assignment)
}

class Assignment {
    Student: List

    getScore()
    setScore()
}

class Student{
    assignment: List

    countMissingAssignment()
    getScoreForAssignment()
    setScoreForAssignment()
}



Gradebook o--> Student
Student o--> Assignment

@enduml